name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install backend depencies
        run: | 
          cd backend
          go mod tidy

      - name: Install frontend dependencies
        run: |
          cd client
          npm install
        
      - name: Run backend tests
        run: |
          cd backend
          go test ./...

      - name: Build Docker images
        run: |
          docker build -t my-backend:latest .
          docker build -t my-frontend:latest ./client

      - name: Push Docker images (optional)
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{  secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-backend:latest mydockerhubusername/my-backend:latest
          docker push mydockerhubusername/my-backend:latest
          docker tag my-frontend:latest mydockerhubusername/my-frontend:latest
          docker push mydockerhubusername/my-frontend:latest